language: dart

dist: bionic
services:
  - xvfb

branches:
  only:
    - master

dart:
  - dev

cache:
  directories:
    - "$HOME/.pub-cache"

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:jonathonf/vim'
    packages:
      - vim-gnome

script:
  - test/travis.sh
