language: dart

dist: bionic
services:
  - xvfb

branches:
  only:
    - master

dart:
  - dev

cache:
  directories:
    - "$HOME/.pub-cache"

addons:
  apt:
    update: true
    packages:
      - python3
      - python3-pip
      - python3-setuptools
      - vim: 'ppa:jonathonf/vim'

before_install:
  - pip3 install --user vim-vint

script:
  - vint .
  - test/travis.sh
