name: integration tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  dart-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Run integration tests
    runs-on: ${{ matrix.os }}

    steps:
    - uses: dart-lang/setup-dart@v0.3
      with:
        sdk: stable
    - uses: rhysd/action-setup-vim@v1
      with:
        version: nightly
    - name: check vim
      run: vim --version; vim --version | grep +clientserver
    - name: checkout
      uses: actions/checkout@v2
    - name: pub upgrade
      working-directory: test/integration
      run: pub upgrade
    - name: run integration tests
      uses: GabrielBB/xvfb-action@v1
      with:
        working-directory: test/integration
        run: pub run test
