name: integration tests

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  dart-tests:
    strategy:
      matrix:
        os: [ubuntu-latest]

    name: Run integration tests
    runs-on: ${{ matrix.os }}

    steps:
    - uses: dart-lang/setup-dart@v1.3
      with:
        sdk: 2.19.0
    - name: checkout
      uses: actions/checkout@v2
    - name: dart pub upgrade
      working-directory: test/integration
      run: dart pub upgrade
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: workflow/nix-shell-action@v3.0.2
      with:
        packages: xvfb-run,vim_configurable
        script: cd test/integration/; xvfb-run dart test
